import 'dotenv/config';
import { PrismaClient } from '../src/generated/prisma/client';
import { PrismaPg } from '@prisma/adapter-pg';

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! });
const prisma = new PrismaClient({ adapter });

async function main() {
  console.log('🌱 지자체 담당자 연락처 시드 시작...');
  await prisma.localGovContact.deleteMany({});
  const data = [
    {
      region: "경상",
      city: "창원시",
      cardName: "창원희망카드,POP카드",
      allowedItems: undefined,
      department: "아동청소년과",
      contactName: "이보람 주무관",
      jobDuty: "급식",
      phone: "055-225-4186",
      email: "cw1125@korea.kr",
      cardBinNo: "7142-4812,4813 4814,4815,4820 아동센터 7142-88",
    },
    {
      region: "경상",
      city: "창원시",
      cardName: "창원희망카드,POP카드",
      allowedItems: undefined,
      department: "아동청소년과",
      contactName: "김진미 주무관",
      jobDuty: "아동보육교사",
      phone: "055-225-3808",
      email: "zim0809@korea.kr",
      cardBinNo: "7142-4812,4813 4814,4815,4820 아동센터 7142-88",
    },
    {
      region: "경상",
      city: "창원시",
      cardName: "창원희망카드,POP카드",
      allowedItems: undefined,
      department: "아동청소년과",
      contactName: "최화형 주무관",
      jobDuty: "아동센터",
      phone: "055-225-3914",
      email: "mirr314@korea.kr",
      cardBinNo: "7142-4812,4813 4814,4815,4820 아동센터 7142-88",
    },
    {
      region: "경상",
      city: "김해시",
      cardName: "꿈자람카드",
      allowedItems: "컵라면",
      department: "아동청소년과",
      contactName: "이연지 주무관",
      jobDuty: "아동센터",
      phone: "055-330-6759",
      email: "abwldi@korea.kr",
      cardBinNo: "7142-4825",
    },
    {
      region: "경상",
      city: "김해시",
      cardName: "꿈자람카드",
      allowedItems: "컵라면",
      department: "아동청소년과",
      contactName: "장연자 주무관",
      jobDuty: "아동센터",
      phone: "055-330-6757",
      email: "doublesk2@korea.kr",
      cardBinNo: "7142-4825",
    },
    {
      region: "경상",
      city: "김해시",
      cardName: "꿈자람카드",
      allowedItems: "컵라면",
      department: "아동청소년과",
      contactName: "남은경 주무관",
      jobDuty: "다함께돌봄센터",
      phone: "055-330-6755",
      email: "semi76@korea.kr",
      cardBinNo: "7142-4825",
    },
    {
      region: "경상",
      city: "밀양시",
      cardName: "미르카드",
      allowedItems: "컵라면",
      department: "여성가족과",
      contactName: "조은유 주무관",
      jobDuty: "급식",
      phone: "055-359-5172",
      email: "joeun229@korea.kr",
      cardBinNo: "7142-4827",
    },
    {
      region: "경상",
      city: "밀양시",
      cardName: "미르카드",
      allowedItems: "컵라면",
      department: "여성가족과",
      contactName: "김아람 주무관",
      jobDuty: "아동센터",
      phone: "055-359-6006",
      email: "ariram@korea.kr",
      cardBinNo: "7142-4827",
    },
    {
      region: "경상",
      city: "밀양시",
      cardName: "미르카드",
      allowedItems: "컵라면",
      department: "회계과",
      contactName: "김현지 주무관",
      jobDuty: "아동센터회계",
      phone: "055-359-5148",
      email: "kjane312@korea.kr",
      cardBinNo: "7142-4827",
    },
    {
      region: "경상",
      city: "사천시",
      cardName: "사천행복카드",
      allowedItems: "컵라면",
      department: "여성가족과",
      contactName: "한보람 주무관",
      jobDuty: "급식/센터",
      phone: "055-831-2672",
      email: "kr1004br@korea.kr",
      cardBinNo: "7142-4824",
    },
    {
      region: "경상",
      city: "고성군",
      cardName: "고성행복카드",
      allowedItems: "봉지/컵라면",
      department: "교육청소년과",
      contactName: "배원경 주무관",
      jobDuty: "급식",
      phone: "055-670-2627",
      email: "baewg@korea.kr",
      cardBinNo: "7142-4882",
    },
    {
      region: "경상",
      city: "고성군",
      cardName: "고성행복카드",
      allowedItems: "봉지/컵라면",
      department: "교육청소년과",
      contactName: "최미혜 주무관",
      jobDuty: "꿈키움",
      phone: "055-670-4663",
      email: "mihye86@korea.kr",
      cardBinNo: "7142-5548",
    },
    {
      region: "경상",
      city: "창녕군",
      cardName: "창녕행복카드",
      allowedItems: "봉지/컵라면",
      department: "행복나눔과",
      contactName: "구민아 주무관",
      jobDuty: "아동센터",
      phone: "055-530-1423",
      email: "buzz98@korea.kr",
      cardBinNo: "7142-4874",
    },
    {
      region: "경상",
      city: "통영시",
      cardName: undefined,
      allowedItems: "봉지/컵라면",
      department: "여성가족과",
      contactName: "박한솔 주무관",
      jobDuty: "아동센터",
      phone: "055-650-4622",
      email: "hansol8710@korea.kr",
      cardBinNo: "7142-4822",
    },
    {
      region: "경상",
      city: "거제시",
      cardName: undefined,
      allowedItems: "봉지/컵라면",
      department: "아동청소년과",
      contactName: "최귀향 주무관",
      jobDuty: "급식/체험카드",
      phone: "055-639-4764",
      email: "hyang0715@korea.kr",
      cardBinNo: "7142-4831,5531",
    },
    {
      region: "경상",
      city: "거제시",
      cardName: undefined,
      allowedItems: "봉지/컵라면",
      department: "아동청소년과",
      contactName: "김민경 주무관",
      jobDuty: "아동센터",
      phone: "055-639-3752",
      email: "sailing@korea.kr",
      cardBinNo: "7142-4831,5531",
    },
    {
      region: "경상",
      city: "거제시",
      cardName: undefined,
      allowedItems: "봉지/컵라면",
      department: "가족정책과",
      contactName: "윤수림 주무관",
      jobDuty: "양육바우처",
      phone: "055-639-4934",
      email: "cosmos447@korea.kr",
      cardBinNo: "7142-5139",
    },
    {
      region: "경상",
      city: "남해군",
      cardName: undefined,
      allowedItems: "봉지/컵라면",
      department: "청년혁신과",
      contactName: "이혜민 주무관",
      jobDuty: "아동센터",
      phone: "055-860-8650",
      email: "flgpals930@korea.kr",
      cardBinNo: undefined,
    },
    {
      region: "경상",
      city: "함양군",
      cardName: undefined,
      allowedItems: "봉지/컵라면",
      department: "사회복지과",
      contactName: "김갑인 주무관",
      jobDuty: "꿈드림",
      phone: "055-960-4844",
      email: "hahagoijn@korea.kr",
      cardBinNo: undefined,
    },
    {
      region: "경상",
      city: "거창군",
      cardName: undefined,
      allowedItems: "봉지/컵라면",
      department: "인구교육과",
      contactName: "정순응 주무관",
      jobDuty: "꿈키움",
      phone: "055-940-8702",
      email: "zegom@korea.kr",
      cardBinNo: "7142-5535",
    },
    {
      region: "경상",
      city: "거창군",
      cardName: undefined,
      allowedItems: "봉지/컵라면",
      department: "복지정책과",
      contactName: "오새해 주무관",
      jobDuty: "어르신",
      phone: "055-940-3092",
      email: "togo111@korea.kr",
      cardBinNo: "7142-5585",
    },
    {
      region: "경상",
      city: "거창군",
      cardName: undefined,
      allowedItems: "봉지/컵라면",
      department: "행복나눔과",
      contactName: "김선영 주무관",
      jobDuty: "아동센터",
      phone: "055-940-3783",
      email: "presentoy@korea.kr",
      cardBinNo: "7142-5579",
    },
    {
      region: "경상",
      city: "문경시",
      cardName: undefined,
      allowedItems: "봉지/컵라면",
      department: "교육지원과",
      contactName: "김소영 주무관",
      jobDuty: "아동 꿈키움",
      phone: "054-550-6616",
      email: "mayer3@korea.kr",
      cardBinNo: "7142-5564",
    },
    {
      region: "충청",
      city: "홍성군",
      cardName: "꿈자람카드",
      allowedItems: "컵라면",
      department: "가정행복과",
      contactName: "황해정 주무관",
      jobDuty: "급식",
      phone: "041-630-1939",
      email: "ritahwang@korea.kr",
      cardBinNo: "7142-4480",
    },
    {
      region: "충청",
      city: "서산시",
      cardName: "꿈자람카드",
      allowedItems: "컵라면",
      department: "가족지원과",
      contactName: "이어진 주무관",
      jobDuty: "급식",
      phone: "041-660-2667",
      email: "djwlss@korea.kr",
      cardBinNo: "7142-4421 7142-41**",
    },
    {
      region: "충청",
      city: "서산시",
      cardName: "꿈자람카드",
      allowedItems: "컵라면",
      department: "가족지원과",
      contactName: "최유정 주무관",
      jobDuty: "아동센터",
      phone: "041-660-3054",
      email: "mjsy3@korea.kr",
      cardBinNo: "7142-4421 7142-41**",
    },
    {
      region: "충청",
      city: "청양군",
      cardName: undefined,
      allowedItems: "컵라면",
      department: "복지정책과",
      contactName: "김지형 주무관",
      jobDuty: "꿈키움",
      phone: "041-940-2613",
      email: "kjh0620@korea.kr",
      cardBinNo: "7142-5579",
    },
    {
      region: "충청",
      city: "제천시",
      cardName: undefined,
      allowedItems: "컵라면",
      department: "여성가족과",
      contactName: "박지연 주무관",
      jobDuty: "꿈모아",
      phone: "043-641-5473",
      email: "pjy66311@korea.kr",
      cardBinNo: "7142-5515",
    },
    {
      region: "충청",
      city: "옥천군",
      cardName: undefined,
      allowedItems: "컵라면",
      department: "행복교육과",
      contactName: "박유진 주무관",
      jobDuty: "꿈키움",
      phone: "043-730-4983",
      email: "pyj00310@korea.kr",
      cardBinNo: "7142-5543",
    },
    {
      region: "충청",
      city: "보은군",
      cardName: undefined,
      allowedItems: "컵라면",
      department: "주민행복과",
      contactName: "강재원 주무관",
      jobDuty: "꿈키움",
      phone: "043-540-3626",
      email: "won29495@korea.kr",
      cardBinNo: "7142-5545",
    },
    {
      region: "충청",
      city: "보은군",
      cardName: undefined,
      allowedItems: "컵라면",
      department: "주민행복과",
      contactName: "이정희 주무관",
      jobDuty: "양육비",
      phone: "043-540-3833",
      email: "leejungod9@korea.kr",
      cardBinNo: "7142-5551",
    },
    {
      region: "충청",
      city: "충주시",
      cardName: undefined,
      allowedItems: "컵라면",
      department: "여성청소년과",
      contactName: "김도경 주무관",
      jobDuty: "문화바우처",
      phone: "043-850-6872",
      email: "dokyeong11@korea.kr",
      cardBinNo: "7142-5546",
    },
    {
      region: "충청",
      city: "영동군",
      cardName: undefined,
      allowedItems: "컵라면",
      department: "가족행복과",
      contactName: "이수연 주무관",
      jobDuty: "교육바우처",
      phone: "043-740-3773",
      email: "sueleedue@korea.kr",
      cardBinNo: "7142-5533",
    },
    {
      region: "충청",
      city: "영동군",
      cardName: undefined,
      allowedItems: "컵라면",
      department: "주민복지과",
      contactName: "오강현 주무관",
      jobDuty: "어르신",
      phone: "043-740-3357",
      email: "jabez84@korea.kr",
      cardBinNo: "7142-5133",
    },
    {
      region: "전북",
      city: "장수군",
      cardName: undefined,
      allowedItems: "컵라면",
      department: "행정지원과",
      contactName: "빈은서 주무관",
      jobDuty: "꿈키움",
      phone: "063-350-2168",
      email: "bin0803@korea.kr",
      cardBinNo: "7142-5532",
    },
    {
      region: "전남",
      city: "진도군",
      cardName: undefined,
      allowedItems: "컵라면",
      department: "가족행복과",
      contactName: "김다현 주무관",
      jobDuty: "꿈키움",
      phone: "061-540-1294",
      email: "di8288@korea.kr",
      cardBinNo: "7142-5537",
    },
    {
      region: "전남",
      city: "진도군",
      cardName: undefined,
      allowedItems: "컵라면",
      department: "가족행복과",
      contactName: "임지수 주무관",
      jobDuty: "어르신",
      phone: "061-540-1274",
      email: "jindo2240@korea.kr",
      cardBinNo: "7142-5144",
    },
    {
      region: "전남",
      city: "장성군",
      cardName: undefined,
      allowedItems: "컵라면",
      department: "주민복지과",
      contactName: "박진양 주무관",
      jobDuty: "꿈키움",
      phone: "061-390-7416",
      email: "parkjy0921@korea.kr",
      cardBinNo: "7142-5538",
    },
    {
      region: "강원",
      city: "태백시",
      cardName: undefined,
      allowedItems: "컵라면",
      department: "교육과",
      contactName: "함성희 주무관",
      jobDuty: "꿈탄탄",
      phone: "033-550-3855",
      email: "ks21m@korea.kr",
      cardBinNo: "7142-5561",
    },
    {
      region: "강원",
      city: "횡성군",
      cardName: undefined,
      allowedItems: "컵라면",
      department: "가족복지과",
      contactName: "김예림 주무관",
      jobDuty: "희망채움",
      phone: "033-340-5870",
      email: "yell1256@korea.kr",
      cardBinNo: "7142-5562",
    },
    {
      region: "강원",
      city: "평창군",
      cardName: undefined,
      allowedItems: "컵라면",
      department: "인재육성과",
      contactName: "김민재 주무관",
      jobDuty: "꿈키움",
      phone: "033-330-2723",
      email: "minjae5602@korea.kr",
      cardBinNo: "7142-5563, 5131(나다움)",
    },
    {
      region: "경기",
      city: "포천시",
      cardName: undefined,
      allowedItems: "컵라면",
      department: "교육정책과",
      contactName: "정혜진 주무관",
      jobDuty: "문화바우처",
      phone: "031-538-2022",
      email: "jhy2j311@korea.kr",
      cardBinNo: "7142-5571",
    },
    {
      region: "전남",
      city: "목포시",
      cardName: undefined,
      allowedItems: "컵라면",
      department: "드림스타트",
      contactName: "박진경 주무관",
      jobDuty: "아동센터",
      phone: "061-270-4838",
      email: "pingcat0819@korea.kr",
      cardBinNo: undefined,
    },
    {
      region: "전남",
      city: "목포시",
      cardName: undefined,
      allowedItems: "컵라면",
      department: "드림스타트",
      contactName: "김현숙 선생님",
      jobDuty: "아동센터",
      phone: "061-270-8151",
      email: "",
      cardBinNo: undefined,
    },
  ];
  await prisma.localGovContact.createMany({ data });
  console.log(`✅ ${data.length}개 레코드 삽입 완료`);
}

main().catch(console.error).finally(() => prisma.$disconnect());